/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205733;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarriorTest {
    /**
     * 戦士の攻撃がattackの１.５倍になることを検証。これを三回行う。
     * 検証手順
     *  (1) 戦士と敵を準備。defaultの攻撃力を100とし、念のため、HPは高めに設定しておく。
     *  (2) ヒーローが殴り、敵も殴る。この時、敵の受けたダメージが、戦士が受けたダメージの1.5倍になることを期待。
     *  (3) 敵の元々のHPをdofoenemyHPとおいて、ダメージを受けた後の敵のHP分を引いてあげると、
     * 戦士の与えたダメージがわかり、それがdefaultattackに対して、１.５倍になることを確認する。
     */
    @Test
    void attackWithWeponSkillTest() {
        int defaultattack = 100;
        Warrior defaultWarrior = new Warrior("ベディヴィエール",1000,defaultrattack);
        Enemy slime = new Enemy("スライムもどき", 1000, defaultattack);
        for (int i=0;i<3;i++){
            int defoEnemyHP = slime.hitPoint;
            defaultWarrior.attackWithWeponSkill(slime);
            slime.attack(defaultWarrior);
            int damege = defoEnemyHP - slime.hitPoint;
            assertEquals(damege,(int)(defaultattack * 1.5));
        }
    }
}








































































































